@DataProcessingSystem_HostAddress = http://localhost:5056

# @name createTask
POST {{DataProcessingSystem_HostAddress}}/tasks
Content-Type: multipart/form-data; boundary=granica

--granica
Content-Disposition: form-data; name="file"; filename="sprzedaz.csv"
Content-Type: text/csv

produkt,ilosc,cena
Kawa,3,12.50
Herbata,5,8.00
Kawa,2,12.50
--granica--

###

GET {{DataProcessingSystem_HostAddress}}/tasks/{{createTask.response.body.$.id}}
