@DataProcessingSystem_HostAddress = http://localhost:5056

POST {{DataProcessingSystem_HostAddress}}/tasks
Content-Type: application/json

{
  "fileName": "sprzedaz.csv",
  "content": "produkt,ilosc,cena\nKawa,3,12.50\nHerbata,5,8.00\nKawa,2,12.50"
}

###

GET {{DataProcessingSystem_HostAddress}}/tasks/6d870134-62c6-4e26-aaff-9e8322734d96